version: '2'
services:
    teststartjhipster-app:
        image: teststartjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://teststartjhipster-mysql:3306/teststartjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    teststartjhipster-mysql:
        extends:
            file: mysql.yml
            service: teststartjhipster-mysql
